### ISSUE TITLE
Please ensure you have license, code of conduct and contribution guidelines in place

### ISSUE THREAD

**Issue by filmaj** [adobe/aem-guides-wknd#1]
At Adobe, anything that goes open source needs to go through the Open Source Office for approval. Usually, employees fill out a quick and simple form at opensource.corp.adobe.com to kick that process off.

It looks like this repo didn't go through this process. At a minimum, please ensure you have a Adobe-legal-approved license and license headers in place, contribution guidelines that make explicit the signing of Adobe's CLA and Adobe's approved code of conduct.

If the above confuses you, please fill out the form at opensource.corp.adobe.com and we will gladly guide you through this process and ensure everything is ready for the public.

**Comment by godanny86** [comment]
Thank you @filmaj , I have filled out the following: https://git.corp.adobe.com/OpenSourceAdvisoryBoard/opensource_submission_process/issues/391

**Comment by filmaj** [comment]
Thanks for addressing this so quickly!
