### ISSUE TITLE
Update libs

### ISSUE THREAD

**Issue by adolfodepazvela** [adobe/aem-guides-wknd#129]
Hello, 
I got some errors when compiling the UI and in order to deploy the code, I changed some libs versions:

`  "aem-clientlib-generator": "^1.4.3", to
    "aem-clientlib-generator": "^1.7.0",`

and

`  "node-sass": "^4.11.0", to
    "node-sass": "^4.14.1", `

**Comment by godanny86** [comment]
hi @adolfodepazvela what were the errors you got? This project will try to maintain consistency with the AEM Project Archetype https://github.com/adobe/aem-project-archetype so it would be interesting if you see the same issues with projects generated there...

**Comment by adolfodepazvela** [comment]
I will recompile again and I let you know! 

One thing for sure in AEM 6.5 + SP5 (brand new instance JDK 11) the 

aem-guides-wknd.core bundle can't be started. I get 

com.day.cq.search,version=[1.4,2) -- Cannot be resolved
com.day.cq.wcm.api,version=[1.29,2) -- Cannot be resolved
org.apache.commons.lang3,version=[3.10,4) -- Cannot be resolved
org.apache.sling.api.resource,version=[2.12,3) -- Cannot be resolved

Thanks
--

**Comment by godanny86** [comment]
Hi @adolfodepazvela you will need to add the `classic` profile for working with AEM 6.x versions:

```
mvn clean install -PautoInstallSinglePackage -Pclassic
``

https://github.com/adobe/aem-guides-wknd#building-for-aem-6xx
