### ISSUE TITLE
[Data Layer] Include Experience Fragments

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-guides-wknd#135]
Currently components created as Experience Fragments are not being registered with the Adobe Data Layer on pages. This is because the `cq:Conf` property needs to be set at `/content/experience-fragments/wknd`

![image](https://user-images.githubusercontent.com/8974514/94081449-e4557300-fdb3-11ea-9899-9dd941ff8881.png)

**Comment by gabrielwalt** [comment]
For any such issues, please systematically create a corresponding issue for the Archetype where the same configuration also seems to be missing. I've now created the following issue: https://github.com/adobe/aem-project-archetype/issues/517.

Similarly, we should maybe also consider adding a sling:configRef="/conf/${appId}" to that node. My guess is that without that, the PDF component probably doesn't work inside of experience fragments.

**Comment by godanny86** [comment]
hey @gabrielwalt absolutely, will do so going forward.
