### ISSUE TITLE
AEM wknd core bundle not active with AEM 6.5.5

### ISSUE THREAD

**Issue by subratokha** [adobe/aem-guides-wknd#148]
<img width="1614" alt="Screenshot 2020-10-07 at 16 44 09" src="https://user-images.githubusercontent.com/19570236/95347189-eabc1280-08bc-11eb-87b4-5cb3ac2cb54c.png">
Tried deploying the wknd project to AEM 6.5.5. Facing bundle is in installed state issue  with dependencies. I have attached the screen shot. 
AEM version 6.5.5

**Comment by godanny86** [comment]
Hi @subratokha did you add the `classic` profile to your build? See https://github.com/adobe/aem-guides-wknd#building-for-aem-6xx

**Comment by subratokha** [comment]
yes 

> Hi @subratokha did you add the `classic` profile to your build? See https://github.com/adobe/aem-guides-wknd#building-for-aem-6xx

yes

**Comment by godanny86** [comment]
Ok, i'll try and reproduce on my end...curious if you are able to reproduce with Service Pack 6?

**Comment by subratokha** [comment]
He @godanny86 ,

Tried to install the package in 6.5.6 and no luck. it doesn't works. Tried with an upgraded instance from 6.3 to 6.5.6 and also on a stand alone AEM 6.5.6

**Comment by godanny86** [comment]
@subratokha are you sure you are compiling it with the classic profile? 

```
mvn clean install -PautoInstallSinglePackage -Pclassic
```

I tried it myself and wasn't able to reproduce on my end... @davidjgonzalez are you able to look into this?

**Comment by subratokha** [comment]
@godanny86 : I am 100% sure i am compiling it using classic profile

**Comment by subratokha** [comment]
@genlaroche10 : WKND Reference Site - 0.0.4 works fine

**Comment by subratokha** [comment]
@davidjgonzalez : Can you provide the jar Java 8 compiled. Also tried cloning https://github.com/davidjgonzalez/aem-guides-wknd/tree/fix/148 but looks to be an old project.

**Comment by aloneblood** [comment]
Hi 
I'm using the [AEM QuickStart Jar](https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/deploy.html?lang=en) 
AEM version: 6.5.0
Openjdk 11.0.18
Maven 3.9.0

I tried main branch 2.1.3 and aem-guides-wknd-2.1.2 tag (2.1.2) but got the same error.
My command is `mvn clean install -PautoInstallSinglePackage -Pclassic`
