### ISSUE TITLE
WKND 0.0.6 not backwards compatible

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-guides-wknd#149]
There should be a note stating something to the effect of:

WKND 0.0.6 is not backward compatible when installed over prior WKND versions due to changes in WKND component paths. To resolve this:

+ Install WKND 0.0.6 on an AEM environment that does not have a previous WKND version installed.
+ Uninstall the wknd.ui.content package, and ensure it removes /content/wknd, /content/experience-fragments/wknd and /conf/wknd, and then install the wknd.ui.content.0.0.6.zip package.

**Comment by godanny86** [comment]
The latest version of WKND should always install cleanly on top of an environment. It is expected to install cleanly on an environment that has had a previous version of WKND installed. Therefore we will revert the commits for issue #136 and by default have WKND Sample content update existing content.
