### ISSUE TITLE
Updated WKND version release scheme

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-guides-wknd#150]
It would be nice if WKND project released using semantic versioning (https://semver.org/) to help indicate if a release is:

1. A bug-fix release (build)
1. Introduces a new feature/implementation example (minor)
1. Is a substantial change that breaks backward compatibility w/ prior WKND version (such as 0.0.6 did) (major)

**Comment by godanny86** [comment]
@davidjgonzalez would you recommend cutting another build to match this?
