### ISSUE TITLE
Use nt:unstructured instead of cq:Page for editable templates

### ISSUE THREAD

**Issue by kwin** [adobe/aem-guides-wknd#152]
The nodes at

1. /conf/wknd/settings/wcm
1. /conf/wknd/settings/wcm/policies
1. /conf/wknd/settings/wcm/templates

should be of type `nt:unstructured` instead of `cq:Page` as they don't have the `jcr:content` sub node required for `cq:Pages`

**Comment by godanny86** [comment]
Thanks @kwin! I think projects generated by the AEM Project archetype will also have this behavior. Do you mind cross-posting this to the AEM Project Archetype?

**Comment by kwin** [comment]
Done in https://github.com/adobe/aem-project-archetype/issues/531

**Comment by godanny86** [comment]
Closing this based on the status of: https://github.com/adobe/aem-project-archetype/issues/531
