### ISSUE TITLE
Update to Core Components 2.12.1

### ISSUE THREAD

**Issue by msagolj** [adobe/aem-guides-wknd#159]
Core Components 2.12.0 has been released:
https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.12.0

The WKND guide can be updated accordingly as needed.

**Comment by godanny86** [comment]
Thanks @msagolj !

**Comment by msagolj** [comment]
@godanny86 we had to do a patch release 2.12.11, i updated title of this issue accordingly.
