### ISSUE TITLE
Include localization example of Header/Footer experience fragment

### ISSUE THREAD

**Issue by kwin** [adobe/aem-guides-wknd#160]
Currently the header and footer have hardcoded paths in the language-independent templates (e.g. in https://github.com/adobe/aem-guides-wknd/blob/f7bee6b4cb31017fbb6c27027846ec7c926f4abe/ui.content/src/main/content/jcr_root/conf/wknd/settings/wcm/templates/content-page-template/structure/.content.xml#L19). What is your idea of supporting language-specific experience fragments then?

I think the concept should be extended so that 

- either a localized version of the experienced fragment is either automatically looked up 
- or the path should actually not come from the template's structure content but should be externalized in a context-aware configuration

In any case I would heavily propose to keep the templates language independent.

**Comment by godanny86** [comment]
Hi @kwin great question! The Experience Fragment component will automatically localize the header / footer based on the language hierarchy that the template is used. Checkout the docs: https://docs.adobe.com/content/help/en/experience-manager-core-components/using/get-started/localization.html#example

**Comment by kwin** [comment]
Thanks for clarifying, I indeed was not aware of the feature outlined in https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/experiencefragment/v1/experiencefragment#features.
Would be nice to include at least one example in WKND for that.
