### ISSUE TITLE
Polluted log due to com/adobe/aem/guides/wknd/core/schedulers/SimpleScheduledTask.java

### ISSUE THREAD

**Issue by kwin** [adobe/aem-guides-wknd#168]
The dummy task at https://github.com/adobe/aem-guides-wknd/blob/ea672cec670f4752b40f5f13b70aae756089cf60/core/src/main/java/com/adobe/aem/guides/wknd/core/schedulers/SimpleScheduledTask.java#L33 writes some dummy message to the log file every 30 seconds.

We have some environments where we have WKND deployed as reference site. Reference sites should not contain useless code which pollutes the log. Although the log level is ERROR by default, even debug messages are emitted to the error log due to https://github.com/adobe/aem-guides-wknd/blob/df0019f9aaa892b29f6586a087fcf3dc4c771526/ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config~wknd.cfg.json#L1.

Either remove the class completely or at least make it disabled by default.

**Comment by godanny86** [comment]
Thanks @kwin. Agreed.
