### ISSUE TITLE
Unable to edit page properties | component-basics/start

### ISSUE THREAD

**Issue by HJordan35** [adobe/aem-guides-wknd#188]
I am working through the "Component Basics" portion of the AEM tutorial, and I have run into an issue when attempting to create my first "page". Here are the steps I have executed

- AEM Authoring is running on 4502
- Cloned this repo and checked out _component-basics/start_ branch
- Executed the following command `mvn -PautoInstallPackage -Padobe-public clean install`
- I receive a "BUILD SUCCESS" in the console, and I do not see any errors
- Login to the AEM instance with admin:admin
- Click on the WKND Site and select "Create"
- Select the "Content Page Template"

After I execute those steps, I see the "Create Page" view, but there are no fields or properties available for edit (as shown in the tutorial)
![image](https://user-images.githubusercontent.com/10759121/104327710-adb17e80-54b0-11eb-9e14-a106860b463e.png)

MacOS Catalina 10.15.6
VSCode 1.52.1
Java version 1.0 (1.8.0_271)
AEM quickstart 6.5
Maven 3.6.3 (it's Java version is listed as 13.0.2)

Happy to provide any additional details if necessary

**Comment by godanny86** [comment]
Can you try the command:

```
 mvn -PautoInstallSinglePackage -Padobe-public clean install
```

**Comment by HJordan35** [comment]
Thanks for replying @godanny86 - I ran that command but I am still seeing the same issue from my side (successful build but a blank "properties" page)

**Comment by godanny86** [comment]
ah ok @HJordan35. let me try and reproduce on my end. 
To confirm you don't have any Service Packs installed, it it AEM 6.5.0?

**Comment by HJordan35** [comment]
Thanks - I am not 100% certain to be honest. A co-worker sent me a version of the quickstart JAR file that he has used on his projects. Is there any easy way for me to check that? Is it possible that I simply need to obtain a different version of that JAR?

**Comment by godanny86** [comment]
ah, no problem. I think it should be in the help menu:
![image](https://user-images.githubusercontent.com/8974514/104366581-73ef7080-54ce-11eb-88b4-343ada9dd926.png)
 
Above is from Cloud Service SDK so it is just a date/timestamp

**Comment by HJordan35** [comment]
Yes it is showing 6.5

**Comment by godanny86** [comment]
Hey @HJordan35, I had trouble reproducing this on my end. Some additional questions:

Is this a clean AEM environment? or did you continue from the Project Setup chapter?
Any JavaScript errors in the browser? What Browser? you might try a clean browser session (or incognito mode)

Can you also verify that all the bundles are started and active at: http://localhost:4502/system/console/bundles

![image](https://user-images.githubusercontent.com/8974514/104380895-8ffc0d80-54e0-11eb-9894-8151d45aaca4.png)

**Comment by HJordan35** [comment]
_Is this a clean AEM environment? or did you continue from the Project Setup chapter?_
I did the previous chapter, but I then in the "Component Basics" chapter, I followed the guide and created a brand new directory with the cloned repo from GitHub. The only pieces from the previous chapter I am using are the setup (i.e. settings.xml, quickstart.jar, etc)

_Any JavaScript errors in the browser?_ 
No - only a few deprecation warnings

_What Browser? you might try a clean browser session (or incognito mode)_
Chrome Version 87.0.4280.88 - I also attempted clearing browser cache and incognito but saw no improvements

_Can you also verify that all the bundles are started and active at: http://localhost:4502/system/console/bundles_
Confirmed that all of the bundles appear to be started and active
![image](https://user-images.githubusercontent.com/10759121/104383854-22f37280-54f6-11eb-930c-561ad1cf000a.png)

**Comment by godanny86** [comment]
hmm, everything looks right. The existing pages, like the WKND Site english home page, can you open and edit that? 

You can also try deleting the following nodes using CRXDE-Lite: http://localhost:4502/crx/de/index.jsp#/conf/wknd

`/conf/wknd`
`/content/wknd`

And then re-deploying the code using Maven.

This shouldn't be necessary but as a last resort you could create a clean AEM environment with the quickstart and then re-try deploying the component basics code...

**Comment by HJordan35** [comment]
Seeing a similar issue when trying to edit the home page
![image](https://user-images.githubusercontent.com/10759121/104387263-5802c380-54fc-11eb-92bd-f65a2f950874.png)

No luck with the delete and re-build approach

So for the nuclear option, are you saying to delete the current /author and /publish directories - re-create them, restart the server, and then clone, maven build, etc - or is there more cleaning I should do?

**Comment by godanny86** [comment]
Yes to clean the environment, stop the AEM author instance, remove the `crx-quickstart` folder and then restart the AEM Author instance. if there are no git changes, you should just be able to rebuild and deploy it using Maven.

Before doing that, can you send a screenshot of `/apps/wknd` in CRXDE Lite? It should look like so:

![image](https://user-images.githubusercontent.com/8974514/104388071-4f56c100-54ed-11eb-8e27-01dc729a9b76.png)

**Comment by HJordan35** [comment]
Ok cool - I will try the hard reset tomorrow. Regarding your other request, see below, I dont think I see any discrepancies

![image](https://user-images.githubusercontent.com/10759121/104398763-fb5fd280-5514-11eb-9e0d-e4f3f0c6655b.png)

**Comment by godanny86** [comment]
Hi @HJordan35 we recently released a new version of the tutorial. Feel free to re-open if you still have issues.
