### ISSUE TITLE
Unable to execute mvn clean install -PautoInstallSinglePackage -Pclassic

### ISSUE THREAD

**Issue by chintan97** [adobe/aem-guides-wknd#189]
### Expected Behaviour
mvn clean install -PautoInstallSinglePackage -Pclassic should execute successfully.

### Actual Behaviour
It fails while executing mvn install
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (make-assembly) on project aem-guides-wknd.ui.tests: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single failed: group id '1821992259' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]

#### Steps to Reproduce
Import the package and execute mvn clean install -PautoInstallSinglePackage -Pclassic using eclipse. I am keeping clean install as goals and -PautoInstallSinglePackage -Pclassic as profiles in Maven build configuration.

#### Platform and Version
Localhost - AEM 6.5
macOS Catalina (10.15.7) 

#### Logs taken while reproducing problem
INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.264 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [  6.663 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 11.280 s]
[INFO] WKND Sites Project - UI apps structure ............. SUCCESS [  0.779 s]
[INFO] WKND Sites Project - UI apps ....................... SUCCESS [  3.270 s]
[INFO] WKND Sites Project - UI content .................... SUCCESS [  1.779 s]
[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.126 s]
[INFO] WKND Sites Project - UI sample content ............. SUCCESS [  2.715 s]
[INFO] WKND Sites Project - All ........................... SUCCESS [  2.851 s]
[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [  5.038 s]
[INFO] WKND Sites Project - Dispatcher .................... SUCCESS [  0.048 s]
[INFO] WKND Sites Project - UI Tests ...................... FAILURE [  0.201 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.030 s
[INFO] Finished at: 2021-01-20T11:56:50-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (make-assembly) on project aem-guides-wknd.ui.tests: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single failed: group id '1821992259' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :aem-guides-wknd.ui.tests

**Comment by godanny86** [comment]
hi @chintan97,
I haven't seen this error before. What version of Maven are you using? Can you also try from just a regular command line terminal?

**Comment by chintan97** [comment]
Hey @godanny86 , I am using Apache Maven 3.6.3. I tried from regular command line terminal as well. But getting the same error.

**Comment by godanny86** [comment]
Ah ok. Do you mind seeing if you get the same build error if you generate an AEM 6.5 project via the AEM Project Archetype https://github.com/adobe/aem-project-archetype ?

Generate the project with a command like:

```plain
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=24 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D aemVersion="6.5"
```

Then build/compile with `mvn clean install -PautoInstallSinglePackage`. No need for the `classic` profile, since it will be a 6.5 targeted project....

**Comment by chintan97** [comment]
Hey @godanny86 , I generated project aem-guides-wknd via AEM project Archetype with the command mentioned and it got succeeded.

> [INFO] Reactor Summary for WKND Sites Project - Reactor Project 0.1.1-SNAPSHOT:
> [INFO] 
> [INFO] WKND Sites Project - Reactor Project ............... SUCCESS [ 12.456 s]
> [INFO] WKND Sites Project - Core .......................... SKIPPED
> [INFO] WKND Sites Project - UI Frontend ................... SKIPPED
> [INFO] WKND Sites Project - UI apps structure ............. SKIPPED
> [INFO] WKND Sites Project - UI apps ....................... SKIPPED
> [INFO] WKND Sites Project - UI content .................... SKIPPED
> [INFO] WKND Sites Project - UI config ..................... SKIPPED
> [INFO] WKND Sites Project - UI sample content ............. SKIPPED
> [INFO] WKND Sites Project - All ........................... SKIPPED
> [INFO] WKND Sites Project - Integration Tests ............. SKIPPED
> [INFO] WKND Sites Project - Dispatcher .................... SKIPPED
> [INFO] WKND Sites Project - UI Tests ...................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  22.224 s
> [INFO] Finished at: 2021-01-21T08:48:45-05:00
> [INFO] ------------------------------------------------------------------------

However, when I compile with mvn clean install -PautoInstallSinglePackage, it failed again with same error:

> [INFO] Reactor Summary:
> [INFO] 
> [INFO] WKND Sites Project - Reactor Project 0.1.1-SNAPSHOT  SUCCESS [  0.159 s]
> [INFO] WKND Sites Project - Core 0.1.1-SNAPSHOT ........... SUCCESS [ 22.155 s]
> [INFO] WKND Sites Project - UI Frontend 0.1.1-SNAPSHOT .... SUCCESS [ 11.489 s]
> [INFO] WKND Sites Project - UI apps structure 0.1.1-SNAPSHOT SUCCESS [  0.672 s]
> [INFO] WKND Sites Project - UI apps 0.1.1-SNAPSHOT ........ SUCCESS [  3.207 s]
> [INFO] WKND Sites Project - UI content 0.1.1-SNAPSHOT ..... SUCCESS [  1.427 s]
> [INFO] WKND Sites Project - UI config 0.1.1-SNAPSHOT ...... SUCCESS [  0.102 s]
> [INFO] WKND Sites Project - UI sample content 0.1.1-SNAPSHOT SUCCESS [  3.018 s]
> [INFO] WKND Sites Project - All 0.1.1-SNAPSHOT ............ SUCCESS [  5.765 s]
> [INFO] WKND Sites Project - Integration Tests 0.1.1-SNAPSHOT SUCCESS [ 22.040 s]
> [INFO] WKND Sites Project - Dispatcher 0.1.1-SNAPSHOT ..... SUCCESS [  0.114 s]
> [INFO] WKND Sites Project - UI Tests 0.1.1-SNAPSHOT ....... FAILURE [  0.591 s]
> [INFO] mysite 1.0.0-SNAPSHOT .............................. SKIPPED
> [INFO] My Site - Core 1.0.0-SNAPSHOT ...................... SKIPPED
> [INFO] My Site - UI Frontend 1.0.0-SNAPSHOT ............... SKIPPED
> [INFO] My Site - Repository Structure Package 1.0.0-SNAPSHOT SKIPPED
> [INFO] My Site - UI apps 1.0.0-SNAPSHOT ................... SKIPPED
> [INFO] My Site - UI content 1.0.0-SNAPSHOT ................ SKIPPED
> [INFO] My Site - UI config 1.0.0-SNAPSHOT ................. SKIPPED
> [INFO] My Site - All 1.0.0-SNAPSHOT ....................... SKIPPED
> [INFO] My Site - Integration Tests 1.0.0-SNAPSHOT ......... SKIPPED
> [INFO] My Site - Dispatcher 1.0.0-SNAPSHOT ................ SKIPPED
> [INFO] My Site - UI Tests 1.0.0-SNAPSHOT .................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  01:12 min
> [INFO] Finished at: 2021-01-21T08:50:12-05:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (make-assembly) on project aem-guides-wknd.ui.tests: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single failed: group id '1821992259' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :aem-guides-wknd.ui.tests

**Comment by godanny86** [comment]
hi @chintan97, just to be clear generating a vanilla project (mysite) via the AEM Project Archetype leads to the same error? It sounds like you might be running into something like this: https://stackoverflow.com/questions/33819438/maven-assembly-plugin-group-id-1377585961-is-too-big-error/56278471

It might be related to your underlying environment?

**Comment by godanny86** [comment]
Hi @chintan97 hopefully you solved the issue. Feel free to re-open if not...

**Comment by chintan97** [comment]
Hi @godanny86 , sorry missed update for a long time! Unfortunately I could not resolve the issue. But I could at least run a build and deploy packages in my local by skipping UI Tests which was failing (using -DskipTests). However, the issue is still there. And yes, I believe the issue might get fixed by updating pom.xml (not sure if missing of <tarLongFileMode>posix</tarLongFileMode> is the issue here or not, just like the user has mentioned in the link you shared).
