### ISSUE TITLE
Dispatcher Build Failure using mvn clean install -PautoInstallSinglePackage

### ISSUE THREAD

**Issue by brianbyars** [adobe/aem-guides-wknd#201]
### Expected Behaviour
BUILD SUCCESS

### Actual Behaviour
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WKND Sites Project - Reactor Project 0.1.1-SNAPSHOT:
[INFO]
[INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.377 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [ 12.779 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 14.380 s]
[INFO] WKND Sites Project - UI apps structure ............. SUCCESS [  1.202 s]
[INFO] WKND Sites Project - UI apps ....................... SUCCESS [ 10.311 s]
[INFO] WKND Sites Project - UI content .................... SUCCESS [  7.939 s]
[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.340 s]
[INFO] WKND Sites Project - UI sample content ............. SUCCESS [  7.455 s]
[INFO] WKND Sites Project - All ........................... SUCCESS [  5.771 s]
[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [ 14.973 s]
[INFO] WKND Sites Project - Dispatcher .................... FAILURE [  0.140 s]
[INFO] WKND Sites Project - UI Tests ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2021-02-19T14:07:33-06:00

#### Steps to Reproduce
Run mvn clean install -PautoInstallSinglePackage from command line

#### Platform and Version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven-3.6.3\bin\..
Java version: 11.0.10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

#### Logs taken while reproducing problem
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WKND Sites Project - Reactor Project 0.1.1-SNAPSHOT:
[INFO]
[INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.377 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [ 12.779 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 14.380 s]
[INFO] WKND Sites Project - UI apps structure ............. SUCCESS [  1.202 s]
[INFO] WKND Sites Project - UI apps ....................... SUCCESS [ 10.311 s]
[INFO] WKND Sites Project - UI content .................... SUCCESS [  7.939 s]
[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.340 s]
[INFO] WKND Sites Project - UI sample content ............. SUCCESS [  7.455 s]
[INFO] WKND Sites Project - All ........................... SUCCESS [  5.771 s]
[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [ 14.973 s]
[INFO] WKND Sites Project - Dispatcher .................... FAILURE [  0.140 s]
[INFO] WKND Sites Project - UI Tests ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by godanny86** [comment]
hey @brianbyars was there any additional info logged about why the dispatcher build failed?

**Comment by brianbyars** [comment]
@godanny86 I have attached the full log
[WKND.txt](https://github.com/adobe/aem-guides-wknd/files/6012818/WKND.txt)

**Comment by godanny86** [comment]
Thanks @brianbyars. When you open the terminal to build the project, can you use the "Run as administrator" mode?

**Comment by brianbyars** [comment]
@godanny86 I ran as admin and got the same failure.  Logs attached
[WKND2.txt](https://github.com/adobe/aem-guides-wknd/files/6012910/WKND2.txt)

**Comment by godanny86** [comment]
Thanks @brianbyars, I think a few Windows users have experienced this issue with maven enforcer plugin for the dispatcher. 

quick work around: add `-Denforcer.skip=true` to your maven command. 

If you have the time, do you mind deleting your maven repository under `.m2/repository` and then retrying the build to see if that changes anything? Warning, this might take several minutes because it will have to re-download all the dependencies.

**Comment by godanny86** [comment]
actually @brianbyars do you mind testing this branch: https://github.com/adobe/aem-guides-wknd/tree/ISSUE-201/dispatcher-build-windows ?

**Comment by brianbyars** [comment]
[INFO] Reading assembly descriptor: C:\AEM\aem-guides-wknd\ui.tests/assembly-ui-test-docker-context.xml
[INFO] Building tar: C:\AEM\aem-guides-wknd\ui.tests\target\aem-guides-wknd.ui.tests-0.1.1-SNAPSHOT-ui-test-docker-context.tar.gz
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ aem-guides-wknd.ui.tests ---
[INFO] Installing C:\AEM\aem-guides-wknd\ui.tests\pom.xml to C:\Users\brian.byars\.m2\repository\com\adobe\aem\guides\aem-guides-wknd.ui.tests\0.1.1-SNAPSHOT\aem-guides-wknd.ui.tests-0.1.1-SNAPSHOT.pom
[INFO] Installing C:\AEM\aem-guides-wknd\ui.tests\target\aem-guides-wknd.ui.tests-0.1.1-SNAPSHOT-ui-test-docker-context.tar.gz to C:\Users\brian.byars\.m2\repository\com\adobe\aem\guides\aem-guides-wknd.ui.tests\0.1.1-SNAPSHOT\aem-guides-wknd.ui.tests-0.1.1-SNAPSHOT-ui-test-docker-context.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WKND Sites Project - Reactor Project 0.1.1-SNAPSHOT:
[INFO]
[INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.434 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [ 10.868 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 14.021 s]
[INFO] WKND Sites Project - UI apps structure ............. SUCCESS [  1.045 s]
[INFO] WKND Sites Project - UI apps ....................... SUCCESS [ 16.184 s]
[INFO] WKND Sites Project - UI content .................... SUCCESS [ 13.084 s]
[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.360 s]
[INFO] WKND Sites Project - UI sample content ............. SUCCESS [  7.029 s]
[INFO] WKND Sites Project - All ........................... SUCCESS [  5.929 s]
[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [ 10.874 s]
[INFO] WKND Sites Project - Dispatcher .................... SUCCESS [  0.144 s]
[INFO] WKND Sites Project - UI Tests ...................... SUCCESS [  5.414 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 min
[INFO] Finished at: 2021-02-19T15:17:58-06:00
[INFO] ------------------------------------------------------------------------

Thank you @godanny86.  Appending -Denforcer.skip=true seemed to work!  The only issue I have not is that my content pages do not seem to be showing content.  Any thoughts on this?  WeRetail appears just fine.

![image](https://user-images.githubusercontent.com/79335762/108576595-cdc03300-72e3-11eb-849a-868323127117.png)

**Comment by godanny86** [comment]
Hey @brianbyars great! I'm assuming you are on 6.5? You will need to append the `-Pclassic` profile. So the command would look like:

```
mvn clean install -PautoInstallSinglePackage -Pclassic -Denforcer.skip=true
```

**Comment by brianbyars** [comment]
@godanny86 Its all good now.  You are the best!

**Comment by godanny86** [comment]
Nice! any time!

**Comment by epsilon-dilrao** [comment]
content pages are blank...
