### ISSUE TITLE
Update to Core Components 2.15.2

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-guides-wknd#204]
Core Components 2.15.0 has been released:
https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.15.0

Update WKND project to the lastest version.

**Comment by godanny86** [comment]
Thanks @jckautzmann ! Any idea when 2.15.0 will be in AEM as a Cloud Service?

**Comment by jckautzmann** [comment]
@godanny86 2.15.0 has been successfully merged into AEM Quickstart. As soon as the new AEM image is validated, it will be deployed to AEMaaCS.

**Comment by godanny86** [comment]
Thanks @jckautzmann will wait to merge until then. I think otherwise the Core bundle will break since we use Core Component APIs in several of the Sling Models.

**Comment by vladbailescu** [comment]
https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.15.2 was released yesterday and will soon be available for AEMaaCS too, updating the scope of this issue to include the new version.
