### ISSUE TITLE
Content pages do not show content

### ISSUE THREAD

**Issue by pryelluw** [adobe/aem-guides-wknd#206]
### Expected Behaviour

Following the tutorial for IntelliJ here:https://experienceleague.adobe.com/docs/experience-manager-learn/foundation/development/set-up-a-local-aem-development-environment.html?lang=en#intellij-idea

WKND site should build and content should be visible.

### Actual Behaviour

Build completes with no error. 
Content is not showing up when selecting it and clicking "edit".

#### Platform and Version

OSX 10.15.4
AEM 6.5.0

#### Additional info

While searching for a solution, I ran into this comment on a recently closed issue: https://github.com/adobe/aem-guides-wknd/issues/201#issuecomment-782487598

Running the maven command on the command line fixed the problem.

However, I was not able to fix it through IntelliJ.

Please let me know if you need more data.

**Comment by pryelluw** [comment]
In the IntelliJ Maven Profile options selecting "classic" seems to have fixed the issue.

<img width="315" alt="Screen Shot 2021-03-01 at 11 34 51 AM" src="https://user-images.githubusercontent.com/33432803/109527987-41033b00-7a82-11eb-9195-f9ce6decd37f.png">

**Comment by godanny86** [comment]
hi @pryelluw, yes you are correct, the `classic` profile needs to be added when deploying WKND to AEM 6.5. We recently modified that project to be backwards compatible with 6.5 and cloud service. We have the instructions updated in most location but clearly missed one. Sorry for the frustration, will get this updated shortly!

**Comment by pryelluw** [comment]
Great, thank you!
I'm glad it wasn't just me 🙂

I can add the info to this repo's README. Would that work? @godanny86

**Comment by godanny86** [comment]
Hi @pryelluw we have it listed here: https://github.com/adobe/aem-guides-wknd/#building-for-aem-6xx but maybe we need to move it higher? relabel it?

**Comment by pryelluw** [comment]
I'd say adding a small part for IntelliJ (and other IDEs) that mentions adding the classic mode as the screenshot above.

Maybe something like:

### Building for AEM 6.x.x

The project has been designed for **AEM as a Cloud Service**. The project is also backward compatible with AEM **6.4.8** and **6.5.5** by adding the `classic` profile when executing a build, i.e:

    mvn clean install -PautoInstallSinglePackage -Pclassic

#### When using IntelliJ

Make sure to check `classic` in your Maven Profile tab.
See example below:

<img width="315" alt="Screen Shot 2021-03-01 at 11 34 51 AM" src="https://user-images.githubusercontent.com/33432803/109532613-4911a980-7a87-11eb-9b68-648d9d4d5c72.png">

**Comment by pryelluw** [comment]
@godanny86 what do you think sir?

**Comment by godanny86** [comment]
Nice! Can you make it slightly more generic? i.e "When using an IDE like IntelliJ" ?

**Comment by godanny86** [comment]
Feel free to PR it up

**Comment by pryelluw** [comment]
Yes, will do so. Thank you for your help @godanny86 
Will close issue when PR is created.

**Comment by godanny86** [comment]
Thanks @pryelluw, closing this as the pr is merged.

**Comment by pryelluw** [comment]
Thank you for the opportunity to contribute! @godanny86 🙏

**Comment by moblizeit** [comment]
i am trying command line and also via visual studio code and get this error

The requested profile "classic" could not be activated because it does not exist.


for running
mvn clean install -PautoInstallSinglePackage -Pclassic

**Comment by mschmid42** [comment]
same as moblizeit, classis does not appear to be a profile; the main us > en page is blank which is why I am here...
