### ISSUE TITLE
Imported packages cannot be resolved

### ISSUE THREAD

**Issue by pryelluw** [adobe/aem-guides-wknd#208]
### Expected Behaviour

Project should build according to instructions in https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/custom-component.html?lang=en

### Actual Behaviour

Build fails with error that  imported packages cannot be resolved.

### Reproduce Scenario (including but not limited to)

- AEM 6.5
- github.com/adobe/aem-guides-wknd on branch `tutorial/custom-component-start`

#### Steps to Reproduce

- Checkout the branch `tutorial/custom-component-start`
- In root directory run `mvn clean install -PautoInstallSinglePackage -Pclassic`

#### Platform and Version

AEM 6.5

#### Logs taken while reproducing problem

```
Symbolic Name | aem-guides-wknd.core

Version | 0.0.1.SNAPSHOT

Bundle Location | jcrinstall:/apps/wknd/install/aem-guides-wknd.core-0.0.1-SNAPSHOT.jar

Last Modification | Wed Mar 10 09:11:51 EST 2021

Description | Core bundle for WKND Sites Project

Start Level | 20


Imported Packages 

com.day.cq.wcm.api,version=[1.28,2) -- Cannot be resolved

org.apache.sling.api.servlets,version=[2.3,3) -- Cannot be resolved
```

The references to these packages are found below:

https://github.com/adobe/aem-guides-wknd/blob/master/core/pom.xml#L170

https://github.com/adobe/aem-guides-wknd/blob/master/core/pom.xml#L172

#### Related 

https://github.com/adobe/aem-guides-wknd/issues/93

#### Misc.

IntelliJ (latest) on Mac

**Comment by godanny86** [comment]
hey @pryelluw is this 6.5.0? Or do you have the latest service pack installed?

**Comment by pryelluw** [comment]
@godanny86 

-  AEM 6.5.0

- I was not aware of a service pack. May you point me towards it?

Thank you!

**Comment by godanny86** [comment]
Sure thing: https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/cq650/servicepack/aem-service-pkg-6.5.7.zip

Sorry, the SP requirement is a bit hidden in the overview https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/overview.html?lang=en#required-software

**Comment by pryelluw** [comment]
Awesome. I'll go ahead and work through this and report back.
@godanny86 ✌️

**Comment by pryelluw** [comment]
@godanny86

Installing AEM service package 6.5.7 solved the issue.

I had to request access to download the latest service package. This was done through support.

Once downloaded, I installed it though the CRX package manager. Pretty seamless!

Thank you for your service!
