### ISSUE TITLE
Provide default cache control headers optimized high cache hit ratio on CDN

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-guides-wknd#220]
### Expected Behaviour

Most of the site resources get delivered by the CDN, to achieve fast loading site globally. Changes published, should be served by the CDN within 10min after publishing.

### Actual Behaviour

Most resources don't have cache control headers, hence a lot of content is served from origin, which makes the site load slow in a lot of ares in the world

**Comment by godanny86** [comment]
@keepthebyte I know you were doing some experimentation with dispatcher configurations. Do you have those settings handy?
