### ISSUE TITLE
Update Core Components to 2.16.0

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-guides-wknd#233]
Core Components 2.16.0 has been released https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.16.0

This Version contains several improvements regarding accessibility for a variety of components like Title, Carousel and more.

Once it's available for AEMaaCS the WKND should update to this version to benefit from this improvements which should be validated via Google Lighthouse.

**Comment by godanny86** [comment]
awesome! Congrats on the release!
