### ISSUE TITLE
Is the packaging of ui.config as container correct? 

### ISSUE THREAD

**Issue by ielali** [adobe/aem-guides-wknd#242]
The documentation lists ui.apps and ui.config as code packages here https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html?lang=en#code-packages-%2F-osgi-bundles

I fail to understand why it's being listed as container for ui.config , can anyone share any insight. Containers are not meant to contain OSGi configs, again according to the official documentation ...
https://github.com/adobe/aem-guides-wknd/blob/0774ee82a03b55213c1be1d0cfd76a07777cb418/ui.config/pom.xml 
<packageType>container</packageType>

**Comment by godanny86** [comment]
hi @ielali I think you may have stumbled on an oversight in this project and in the AEM Project archetype https://github.com/adobe/aem-project-archetype. Is there a specific behavior that the `container` packaging is breaking for you?

**Comment by ielali** [comment]
Hello @godanny86 thanks for the prompt reply! no nothing breaking at the moment deployment wise, it's just that I was preparing a presentation on AEM as a cloud service and I couldn't explain why the config was categorised as container package. The documentation actually doesn't explain either why we needed a dedicated package for OSGi config for that matter.

**Comment by godanny86** [comment]
Hi @ielali nice, you have a great eye for detail! I'm seeing some inconsistencies with [0] vs. the Jackrabbit docs [1]. The Jackrabbit docs seem to imply that `container` is correct. I'll circle back with the documentation team and get an update. I believe that AEMaaCS OSGi configurations have slightly different lifecycle, whereas ui.apps will be baked into the image. Again I'll try and dig up some good answers for you :) 

[0] - https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html?lang=en#code-packages-%2F-osgi-bundles
[1] - http://jackrabbit.apache.org/filevault-package-maven-plugin/generate-metadata-mojo.html

**Comment by godanny86** [comment]
hi @ielali the `container` packaging type is correct for `ui.config`. The docs at https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html?lang=en#code-packages-%2F-osgi-bundles will be updated.
