### ISSUE TITLE
Syncing with Archetype 28's immutable files update from Dispatcher SDK 2.0.57 and opt-in marker file for direct sources mode

### ISSUE THREAD

**Issue by krystiannowak** [adobe/aem-guides-wknd#246]
### Expected Behaviour
WKND's dispatcher configs are in sync with [AEM CS Archetype](https://github.com/adobe/aem-project-archetype)'s dispatcher configs, Dispatcher SDK configs and the ones used in AEM CS runtime.

### Actual Behaviour
WKND needs and update from changes in Archetype 28:
- [https://github.com/adobe/aem-project-archetype/issues/668](https://github.com/adobe/aem-project-archetype/issues/668)
- [https://github.com/adobe/aem-project-archetype/pull/669](https://github.com/adobe/aem-project-archetype/pull/669)
- [https://github.com/adobe/aem-project-archetype/issues/703](https://github.com/adobe/aem-project-archetype/issues/703)
- [https://github.com/adobe/aem-project-archetype/pull/704](https://github.com/adobe/aem-project-archetype/pull/704)
- [https://github.com/adobe/aem-project-archetype/issues/715](https://github.com/adobe/aem-project-archetype/issues/715)
- [https://github.com/adobe/aem-project-archetype/pull/716](https://github.com/adobe/aem-project-archetype/pull/716)

#### Steps to Reproduce
Make diff between dispatcher subproject's src directories between WKND and Archetype.

#### Platform and Version
n/a

#### Sample Code that illustrates the problem
n/a

#### Logs taken while reproducing problem
n/a

**Comment by godanny86** [comment]
@krystiannowak what is the timing for this to be merged? Does it need to wait until Archetype 28 is released? There are a few bug fixes for un-related features and we will plan to do a release end of this week.

**Comment by krystiannowak** [comment]
@godanny86 Apart from the last change - https://github.com/adobe/aem-guides-wknd/pull/247/commits/5b4d3174d891b2bee31ba6c297c84b8a9250580f - all the previous ones are already in the [Dispatcher SDK](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/disp-overview.html?lang=en#extracting-the-sdk) 2.0.46 that was released early in April ([along with AEM SDK v2021.4.5129.20210404T142221Z-210325](https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2021.4.5129.20210404T142221Z-210325/)), so probably it would be better even to release it *before* the [Archetype 28](https://github.com/adobe/aem-project-archetype/milestone/22) release. And when the new version of the Archetype is released they will be just aligned (there is no strong need to make them strictly in sync or ordering of the releases, but the more in sync the better of course in long term). The last change would be soon also available in upcoming public release (although also strict sync is not necessary here), so there is a perfect timing if this change is released this week.

**Comment by krystiannowak** [comment]
@godanny86 #247 just got merged to master branch - thanks @gknobloch and @vladbailescu !
