### ISSUE TITLE
Use shortened URL as canonical link

### ISSUE THREAD

**Issue by Buuhuu** [adobe/aem-guides-wknd#268]
### Expected Behaviour

When search on Google, for example, I want to find the wknd site with a properly shortened breadcrumb. 

### Actual Behaviour

![Screenshot 2021-07-19 at 11 31 01](https://user-images.githubusercontent.com/558094/126138121-7ced2018-cf15-4794-8e0f-4e7e6626b6aa.png)

### Reproduce Scenario (including but not limited to)

https://www.google.com/search?q=wknd+site+western+australia&oq=wknd+site+western+australia&aqs=chrome..69i57j69i60.5154j0j4&sourceid=chrome&ie=UTF-8

The problem is in the [apps/wknd/components/page/customheaderlibs.html#L17](https://github.com/adobe/aem-guides-wknd/blob/master/ui.apps/src/main/content/jcr_root/apps/wknd/components/page/customheaderlibs.html#L17) hardcoding the canonical to the wknd.site domain and the full path to the page.

**Comment by Buuhuu** [comment]
This should use the new canonical link feature from sites-seo once available https://github.com/adobe/aem-core-wcm-components/pull/1647

**Comment by keepthebyte** [comment]
this is fixed - retry your google search
