### ISSUE TITLE
WKND Chapter 6 Custom Component - start branch - byline.html isEmpty validation error 

### ISSUE THREAD

**Issue by infiniteshi** [adobe/aem-guides-wknd#286]
### Expected Behaviour
Follow the instructions in Chapter 6 Custom Component, should see Stacey Roswells byline component showing up normally on the page.
### Actual Behaviour
At first, the name wasn't showing up while the occupations and image were fine. When trouble-shooting the name-no-showing error, ran into a MVN build failure with ui.apps. The error message is as follows:
[WARNING] /Users/.../Projects/newWorkspace/wknd-chapter5-v3/aem-guides-wknd/ui.apps/src/main/content/jcr_root/apps/wknd/components/byline/byline.html [12:25]: ${placeholderTemplate.placeholder @ isEmpty=!hasContent}: Unknown option 'isEmpty'.
[INFO] Processed 7 files in 393ms
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for aem-guides-wknd 0.0.1-SNAPSHOT:
[INFO] 
[INFO] aem-guides-wknd .................................... SUCCESS [  0.184 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [  4.216 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 20.861 s]
[INFO] WKND Sites Project - Repository Structure Package .. SUCCESS [  0.732 s]
[INFO] WKND Sites Project - UI apps ....................... FAILURE [  0.531 s]
[INFO] WKND Sites Project - UI content .................... SKIPPED
[INFO] WKND Sites Project - UI config ..................... SKIPPED
[INFO] WKND Sites Project - All ........................... SKIPPED
[INFO] WKND Sites Project - Integration Tests ............. SKIPPED
[INFO] WKND Sites Project - Dispatcher .................... SKIPPED
[INFO] WKND Sites Project - UI Tests ...................... SKIPPED
[INFO] WKND Sites Project - Project Analyser .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.401 s
[INFO] Finished at: 2021-11-02T16:59:44-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.sling:htl-maven-plugin:1.3.4-1.4.0:validate (validate-htl-scripts) on project aem-guides-wknd.ui.apps: Compilation warnings were configured to fail the build. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :aem-guides-wknd.ui.apps

The complaint that ${placeholderTemplate.placeholder @ isEmpty=!hasContent}: Unknown option 'isEmpty'. is out of blue since I changed !hasContent to true for troubleshooting purpose. Somehow that change wasn't picked up.

The suggested  mvn <args> -rf :aem-guides-wknd.ui.apps didn't work out, either.

### Reproduce Scenario (including but not limited to)
start branch
#### Steps to Reproduce
Followed the tutorial instructions. At first I typed in all the code step by step and had the "no name" symptom as described above. Then for sanity test I copied and pasted the code from the tutorial instead, then ran into the MVN build issue.
#### Platform and Version
local AEM instance 6.5 jar, service pack 6.5.10
#### Logs taken while reproducing problem
See actual behavior.

**Comment by godanny86** [comment]
Hi @infiniteshi  Can you paste the full contents of your byline.html file?

**Comment by infiniteshi** [comment]
Hi @godanny86 You were right, it was the byline.html, data-sly-test.hasContent="${byline.empty}" missed the ! before byline.empty. Don't know why it took a text-compare tool to spot that. But it's all good now. Thanks.
