### ISSUE TITLE
Remove hardcoded canonical tag

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-guides-wknd#289]
### Expected Behaviour

https://wknd.site/us/en.html should only have _one_ canonical tag 

### Actual Behaviour

Currently there are two

<link rel="canonical" href="/us/en.html"/>

and 

<link rel="canonical" href="https://wknd.site/content/wknd/us/en.html"/>

in the head.

We should remove the custom tag added customheaderlibs.html - as the Core Components now add a tag by default.

**Comment by godanny86** [comment]
Agreed. Thanks @keepthebyte
