### ISSUE TITLE
Examine CORS & CSRF configurations installed by this project

### ISSUE THREAD

**Issue by AShroti** [adobe/aem-guides-wknd#301]
### Expected Behaviour
This project installed CSRF & CORS configurations that conflict with OOTB AEM. The following configurations need to be examined and adjust/removed to ensure it doesn't conflict with AEM anymore:

https://github.com/adobe/aem-guides-wknd/tree/master/ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author

### Actual Behaviour

The OOTB expected POST/PREFLIGHT requests on **Author** are getting blocked due to custom CSRF & CORS configurations installed by this project.

The configs exist at https://github.com/adobe/aem-guides-wknd/tree/master/ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author

### Reproduce Scenario (including but not limited to)

The content can't be accessed using AEM GraphaQL APIs is this WKND Sites project is installed on the **author** instance.

#### Steps to Reproduce

The Headless Admin App doesn't work with the instance if this WKND Sites project is installed.

**Comment by AShroti** [comment]
As part of the commit, the [WKND specific content endpoint](https://github.com/adobe/aem-guides-wknd/pull/254/commits/b9cf8946136dedb8ff6865337187d0531d57bebe) is introduced and enabled at CSRF configuration. Hence not removing the CSRF config completely, rather just fixing the conflict with the OOTB AEM.
CC: @godanny86

**Comment by AShroti** [comment]
Raised the PR: https://github.com/adobe/aem-guides-wknd/pull/303

**Comment by gknobloch** [comment]
I've seen a suggestion from @jasghar to change the default product config to `/content/cq:graphql/.*/endpoint.json`

**Comment by godanny86** [comment]
yeah if the product open those up by default it would be great, especially since you have the option to publish/unpublish the endpoint...

@AShroti I'm also a little confused as to why a CORs config would conflict with ootb functionality? You can have multiple CORS configs via a factory

**Comment by AShroti** [comment]
> I've seen a suggestion from @jasghar to change the default product config to /content/cq:graphql/.*/endpoint.json

I hope you meant the following:

1. Include the generic config  `/content/cq:graphql/.*/endpoint.json` at the **AEM OOTB** 
2. Then remove the CSRF config altogether from **the WKND Site**

I will raise the PRs on both (AEM OOTB & WKND). Let me know if I have missed something.

**Comment by AShroti** [comment]
> @AShroti I'm also a little confused as to why a CORs config would conflict with ootb functionality? You can have multiple CORS configs via a factory

Yes, there was no conflict in this case. I have restored the CORS config back.
