### ISSUE TITLE
consider switching from "Asar" font to another one

### ISSUE THREAD

**Issue by grubyak** [adobe/aem-guides-wknd#31]
`Asar` font used in wknd does not provide `)` character and shows space instead that can cause a confusion, see:

<img width="1378" alt="screen-shot-20191007-095719" src="https://user-images.githubusercontent.com/1628646/66318129-080d7800-e91b-11e9-83bc-e1a891f325c7.png">

**Comment by godanny86** [comment]
Thanks @grubyak we have moved the standard body text to Source Sans Pro...although the titles still use Asar...
