### ISSUE TITLE
Adobe Wknd Training Issues

### ISSUE THREAD

**Issue by YiXuanSee** [adobe/aem-guides-wknd#326]
I’m trying to run the first project in Archetype 35
![1](https://user-images.githubusercontent.com/93636686/155920902-3abe29a5-d15f-4224-a8a4-0332d4978a2c.jpg)

However, I faced this issue. Are you able to assist us?
![2](https://user-images.githubusercontent.com/93636686/155920954-1d7ecece-f2bd-44e7-9cbe-35e5cc0d870a.jpg)

**Comment by godanny86** [comment]
hi @YiXuanSee 

What version of AEM are you using? Only the latest Cloud Service and AEM 6.5 + Service Pack 10+ are supported.

**Comment by YiXuanSee** [comment]
hi @godanny86 
I am using AEM 6.5.0.
