### ISSUE TITLE
Update to Core Components 2.19.0

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-guides-wknd#335]
Update to the latest released version of Core Components: 
https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.19.0

**Comment by SachinMali** [comment]
I think current WKND version uses [2.19.2](https://github.com/adobe/aem-guides-wknd/blob/main/pom.xml#L63) and seems already incorporated thus closing the issue.
