### ISSUE TITLE
CF Models need reference field default locations updated

### ISSUE THREAD

**Issue by knennigtri** [adobe/aem-guides-wknd#367]
### Expected Behaviour
When creating a WKND content fragment, the reference fields should point me to `/content/dam/wknd-shared` rather than `/content/dam/wknd`.

### Actual Behaviour
All three WKND models use the default path `/content/dam/wknd` in the reference fields which denies access to all the shared WKND assets under `/content/dam/wknd-shared`

#### Steps to Reproduce
1. Go into the dam WKND Shared folder and create a new content fragment
2. Use Article fragment
3. On the Featured Image field, select the browser button and notice that it is pointing to /content/dam/wknd
4. On the Author field, select the browser button and notice that it is pointing to /content/dam/wknd

#### Platform and Version
WKND 2.0.0

**Comment by SachinMali** [comment]
@knennigtri This has been fixed via https://github.com/adobe/aem-guides-wknd-shared/pull/18, it will be released soon.

**Comment by SachinMali** [comment]
This has been fixed, please try via https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-2.1.2 or deploy the `Main` branch if it's a development environment.
