### ISSUE TITLE
AEM Content Missing & React GraphQL Not Working

### ISSUE THREAD

**Issue by seivad** [adobe/aem-guides-wknd#368]
### Expected Behaviour
Utilise the WKND classic package provided here as the latest release and view the example site whilst following the Headless React tutorial

### Actual Behaviour
No Adventures content shows up after running ```mvn clean install -PautoInstallSinglePackage -Pclassic``` or using the upload package system. The react app provided at https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/quick-setup/local-sdk.html?lang=en and CORS here  https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/graphql/quick-setup/local-sdk.html?lang=en#cors-config does not load

Error: PersistenceError: Could not find Persisted Query shows for React app even after following the instructions to enable CORS

### Reproduce Scenario (including but not limited to)
Follow the tutorial, the site is working but the adventure content is completely missing, graphql calls fail with a 404 with more detail when inspecting the XHR response -> details: "Configuration: 'wknd' and Query Name: 'adventures-all' does not resolve to an existing Persistent Query"

#### Steps to Reproduce
Follow the tutorial on a fresh install of everything

#### Platform and Version
Mac OS 12.4, 6.5.10

#### Logs taken while reproducing problem
I have screenshots available but if you follow the tutorial this will happy to you.

**Comment by SachinMali** [comment]
@seivad please try with the latest [WKND Site - v2.1.0](https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-2.1.0) and [React App - WKND Adventures ](https://github.com/adobe/aem-guides-wknd-graphql/tree/main/react-app) but make sure to have AEM 6.5.**13**

Lately, there has been refactoring to adopt
1. Cached Persisted Queries
2. Newer NPM Modules (aem-headless-client-js)
3. Usage of newer REACT Hooks

**Comment by SachinMali** [comment]
Closing cause of inactivity, please reopen it if needed...
