### ISSUE TITLE
Error while building for AEM 6.5.0 for classic profile

### ISSUE THREAD

**Issue by vkambs** [adobe/aem-guides-wknd#373]
HI,
I am trying to build the wknd tutorial for AEM 6.5.0 stand alone jar, I received from Adobe support for training on AEM. I am getting error while trying to build project for classic, using the below command - 
 
**Command**
mvn clean install -PautoInstallSinglePackage -Pclassic

**Error -** 

[INFO] Reactor Summary for WKND Sites Project 0.0.1-SNAPSHOT:
[INFO]
[INFO] WKND Sites Project ................................. SUCCESS [  0.554 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [  9.689 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 17.838 s]
[INFO] WKND Sites Project - Repository Structure Package .. SUCCESS [  1.095 s]
[INFO] WKND Sites Project - UI apps ....................... FAILURE [  1.279 s]
[INFO] WKND Sites Project - UI content .................... SKIPPED
[INFO] WKND Sites Project - UI config ..................... SKIPPED
[INFO] WKND Sites Project - All ........................... SKIPPED
[INFO] WKND Sites Project - Integration Tests ............. SKIPPED
[INFO] WKND Sites Project - UI Tests ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.477 s

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.0.0:clean (default-clean) on project aem-guides-wknd.ui.apps: Failed to clean project: Failed to delete C:\AEM\AEm_Archtype\wknd\aem-guides-wknd\ui.apps\target\generated-sources\htl\org\apache\sling\scripting\sightly\apps\wknd\components\xfpage\customheaderlibs__002e__html.java -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :aem-guides-wknd.ui.apps

**Classic profile** - 
 <profile>
            <id>classic</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.jackrabbit</groupId>
                        <artifactId>filevault-package-maven-plugin</artifactId>
                        <extensions>true</extensions>
                        <configuration>
                            <group>com.adobe.aem.guides</group>
                            <embeddeds>
                                <embedded>
                                    <groupId>com.adobe.aem.guides</groupId>
                                    <artifactId>aem-guides-wknd.ui.apps</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-packages/application/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.aem.guides</groupId>
                                    <artifactId>aem-guides-wknd.core</artifactId>
                                    <target>/apps/wknd-packages/application/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.aem.guides</groupId>
                                    <artifactId>aem-guides-wknd.ui.content</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-packages/content/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.aem.guides</groupId>
                                    <artifactId>aem-guides-wknd.ui.config</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-packages/application/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.aem.guides</groupId>
                                    <artifactId>aem-guides-wknd.ui.content.sample</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-packages/content/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.cq</groupId>
                                    <artifactId>core.wcm.components.content</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-vendor-packages/application/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.cq</groupId>
                                    <artifactId>core.wcm.components.config</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-vendor-packages/application/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.cq</groupId>
                                    <artifactId>core.wcm.components.core</artifactId>
                                    <target>/apps/wknd-vendor-packages/application/install</target>
                                </embedded>
                                <embedded>
                                    <groupId>com.adobe.aem.guides</groupId>
                                    <artifactId>aem-guides-wknd-shared.ui.content</artifactId>
                                    <type>zip</type>
                                    <target>/apps/wknd-vendor-packages/content/install</target>
                                </embedded>                           
                            </embeddeds>
                        </configuration>
                    </plugin>
            </plugins>
            </build>
         </profile>

**If I build the code using below command** - 
mvn clean install -PautoInstallSinglePackage

The code gets built but I am unable to view components in AEM. 

Maven Command used to setup project - 

> 

mvn -B archetype:generate -D archetypeGroupId=com.adobe.aem -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=37 -D appTitle="WKND Sites Project" -D appId="wknd" -D groupId="com.adobe.aem.guides" -D artifactId="aem-guides-wknd" -D package="com.adobe.aem.guides.wknd" -D version="0.0.1-SNAPSHOT" -D aemVersion=6.5.0 -D includeDispatcherConfig=n

>

**Comment by vkambs** [comment]
I got code from here and was able to build successfully....... But I am unable to view components on page to add. The component view is blank. Nothin is comin in the filter.

**Comment by SachinMali** [comment]
@vkambs can you please try with aem service pack 13, you can download and install by following Adobe docs

https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/release-notes.html?lang=en

**Comment by vkambs** [comment]
Installing service pack solved it.
