### ISSUE TITLE
WKND Bundle in installed state

### ISSUE THREAD

**Issue by vkambs** [adobe/aem-guides-wknd#374]
Hi,
I checked out code from git repo and trying to build the code for deploying on stand alone version of 6.5.10. I am using the following command to build / install. I am running this command in main directory - 

mvn clean install -PautoInstallSinglePackage -Pclassic

### Expected Behaviour
Bundle should start

### Actual Behaviour
All modules are getting built, for classic profile cloud modules should not be built - 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WKND Sites Project - Reactor Project 2.1.1-SNAPSHOT:
[INFO]
[INFO] WKND Sites Project - Reactor Project ............... SUCCESS [  0.865 s]
[INFO] WKND Sites Project - Core .......................... SUCCESS [ 13.671 s]
[INFO] WKND Sites Project - UI Frontend ................... SUCCESS [ 28.606 s]
[INFO] WKND Sites Project - UI apps structure ............. SUCCESS [  1.721 s]
[INFO] WKND Sites Project - UI apps ....................... SUCCESS [  6.266 s]
[INFO] WKND Sites Project - UI content .................... SUCCESS [  3.406 s]
[INFO] WKND Sites Project - UI config ..................... SUCCESS [  0.358 s]
[INFO] WKND Sites Project - UI sample content ............. SUCCESS [  4.227 s]
[INFO] WKND Sites Project - All ........................... SUCCESS [02:20 min]
[INFO] WKND Sites Project - Integration Tests ............. SUCCESS [ 17.287 s]
[INFO] WKND Sites Project - UI Tests ...................... SUCCESS [  0.484 s]
[INFO] ------------------------------------------------------------------------

### Reproduce Scenario (including but not limited to)
checkout code and build / install using -> mvn clean install -PautoInstallSinglePackage -Pclassic

#### Platform and Version
AEM 6.5.10

#### Logs taken while reproducing problem
Getting error - 
24.08.2022 11:35:05.886 *ERROR* [qtp1323743071-8581] org.apache.felix.http.jetty Bundles: Cannot start (org.osgi.framework.BundleException: Unable to resolve aem-guides-wknd.core [612](R 612.0): missing requirement [aem-guides-wknd.core [612](R 612.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.search)(version>=1.4.0)(!(version>=2.0.0))) Unresolved requirements: [[aem-guides-wknd.core [612](R 612.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.search)(version>=1.4.0)(!(version>=2.0.0)))])
org.osgi.framework.BundleException: Unable to resolve aem-guides-wknd.core [612](R 612.0): missing requirement [aem-guides-wknd.core [612](R 612.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.search)(version>=1.4.0)(!(version>=2.0.0))) Unresolved requirements: [[aem-guides-wknd.core [612](R 612.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.search)(version>=1.4.0)(!(version>=2.0.0)))]

**Comment by SachinMali** [comment]
@vkambs Can you please try on AEM 6.5.**13** also please see https://github.com/adobe/aem-guides-wknd#system-requirements

**Comment by SachinMali** [comment]
Closing cause of inactivity, please reopen it its not resolved on 6.5.13 also.
