### ISSUE TITLE
Update WKND to use archetype v39 or greater

### ISSUE THREAD

**Issue by jfoxx** [adobe/aem-guides-wknd#386]
### Expected Behaviour

The WKND tutorial has v35 in the build project script. I should be able to build the blank project right away.

### Actual Behaviour

As of v39, all previous versions generated from a new archetype are failing at the ui.frontend build step.

#### Steps to Reproduce
Create a new project as directed in the tutorial using v35 of the archetype.  Build the project and it will fail.

**Comment by SachinMali** [comment]
@jfoxx This has been addressed in this WKND repo and corresponding [Getting Started with AEM Sites - Project Archetype](https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-archetype/overview.html?lang=en)

Please let us know if you come across legacy/old archetype-related information.
