### ISSUE TITLE
Unable to see assets on wknd sites pages

### ISSUE THREAD

**Issue by kgoyal6** [adobe/aem-guides-wknd#390]
### Expected Behaviour
The page should render fully fledged with all the assets shown.
### Actual Behaviour
The page is loading but the assets are not shown
#### Platform and Version
AEM version 6.5

**Comment by SachinMali** [comment]
@kgoyal6 Can you verify if you are on 6.5.**13** or above, please see [system requirements](https://github.com/adobe/aem-guides-wknd#system-requirements).

**Comment by kgoyal6** [comment]
@SachinMali I'm using JDK 11.0.2 and Maven version 3.8.7

**Comment by SachinMali** [comment]
Great, how about AEM version, are there any SP applied, try to be on at least SP-13, here is the link for [SP-15](https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/release-notes.html) and older ones are [here](https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.14.html?lang=en)

**Comment by kgoyal6** [comment]
<img width="400" alt="AEM Version" src="https://user-images.githubusercontent.com/121942224/213214914-ba75ecae-13b4-48f4-b48a-3acbc990c757.PNG">
This is all I found out.

**Comment by kgoyal6** [comment]
@SachinMali I'm not even able to see the page content. It is coming blank now. Any solutions? 
One of my colleagues is using the same SDK and project folder and pages are coming fine for him. Not sure what is the issue.

**Comment by SachinMali** [comment]
@kgoyal6 Can you please review logs, setup or redo the steps, and cross-check with your colleague? This seems specific problem than general problem.
