### ISSUE TITLE
Error while creating AEM project using maven archetype 39

### ISSUE THREAD

**Issue by kgoyal6** [adobe/aem-guides-wknd#391]
I'm using the below command - 
mvn -B archetype:generate -D archetypeGroupId=com.adobe.aem -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=39  -D aemVersion=cloud -D appTitle="CBDT" -D appId="cbdt" -D groupId="com.cbdt" -D frontendModule=general -D includeExamples=n

Error I'm getting - 
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom:

JDK version 11.0.2
Maven version 3.8.7

**Comment by SachinMali** [comment]
Please cross-verify your command and options by comparing them with [AEM Project Archetype::Usage](https://github.com/adobe/aem-project-archetype#usage)

**Comment by kgoyal6** [comment]
I've cross checked, everything looks fine. Still the error is there. Can you share any other criteria that I can cross check?
