### ISSUE TITLE
Expose page content in JSON format

### ISSUE THREAD

**Issue by kgoyal6** [adobe/aem-guides-wknd#393]
I have a requirement where I need to expose page content in the form of JSON where every component data will be a separate object inside the JSON output.

How can I fetch all components separately in my servlet so that I can then fetch their properties and put them in my output?

P.S. I am not using headless approach because of some limitations. For now, I'm using traditional AEM development.

**Comment by SachinMali** [comment]
Please use this project for relevant WKND issues and not general AEM development, as suggested earlier there are AEM communities and [Adobe Experience Manager Tutorials](https://experienceleague.adobe.com/docs/experience-manager-tutorials.html?lang=en) avenues to discuss, brainstorm it.
