### ISSUE TITLE
AEM_6.5_Quickstart incompatibility

### ISSUE THREAD

**Issue by aloneblood** [adobe/aem-guides-wknd#400]
The AEM can not view/edit the WKND site.
I can see the same problem reported on https://github.com/adobe/aem-guides-wknd/issues/148 and fixed on https://github.com/adobe/aem-guides-wknd/pull/151

### Expected Behaviour
I can edit and view wknd pages.

### Actual Behaviour
![iShot_2023-03-25_21 43 04](https://user-images.githubusercontent.com/4945220/227720875-e0f468b3-5b57-4755-9b16-0323020c4bda.jpg)

#### Steps to Reproduce
You can use the main branch or the aem-guides-wknd-2.1.2 tag to run the below command
`mvn clean install -PautoInstallSinglePackage -Pclassic`

#### Platform and Version
MacOS 13.2 (arm64 apple M1)
I'm using the [AEM QuickStart Jar](https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/deploy.html?lang=en)
AEM version: 6.5.0
OpenJDK 11.0.18
Maven 3.9.0

#### Logs taken while reproducing problem
The [WKND Sites Project - Coreaem-guides-wknd.core bundle is installed but inactive.
http://localhost:4502/system/console/bundles
![iShot_2023-03-25_21 39 21](https://user-images.githubusercontent.com/4945220/227720652-77b1605e-f747-48f3-bde0-53469f9863f7.jpg)

**Comment by SachinMali** [comment]
@aloneblood I see you tried on 6.5.0 ([vs 6.5.13.0+](https://github.com/adobe/aem-guides-wknd#system-requirements)). Can you confirm if you still see the issue with Service Pack 13 or later, see the [SP install page](https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/aem-forms-current-service-pack-installation-instructions.html).

**Comment by aloneblood** [comment]
@SachinMali 

I got the AEM_6.5_Quickstart.jar by submit https://solutionpartners.adobe.com/solution-partners/registration.html
I can not download SP from [SP install page](https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/aem-forms-current-service-pack-installation-instructions.html).

**Comment by davidjgonzalez** [comment]
Hi @aloneblood this looks like you are trying to access We.Retail and not WKND.

Can you make sure you are accessing the correct site? If youre still having problems please re-open this issue.
