### ISSUE TITLE
Auto install issue after adding thumnail image - chapter 1

### ISSUE THREAD

**Issue by manisha1146** [adobe/aem-guides-wknd#5]
No steps to add the resource for vault definition in ui.apps/pom.xml and ui.content/pom.xml. Kindly add the steps to include <resource> resource tag in build definition <build> in the documentation
Note: if we change the https to http in .content.xml file inside definition folder. It is working properly. Please update the docs

**Comment by godanny86** [comment]
Thank you @manisha1146 . This has been fixed on the docs: https://github.com/AdobeDocs/experience-manager-learn.en/commit/9bff4ed78e64e32b866addc33b54aea40f449944

Feel free to re-open if you still have issues.
