### ISSUE TITLE
Tags not populating correctly for pages and impacting tabs feature in /adventures.html

### ISSUE THREAD

**Issue by hchung416** [adobe/aem-guides-wknd#63]
![Screen Shot 2019-12-09 at 10 52 04 AM](https://user-images.githubusercontent.com/44936783/70466374-d4b0ac00-1a77-11ea-919c-871069bb2e7d.png)
After installing the latest build (#62 ) on legacy and cloud ready quickstarts (seems to work fine in Skyline), page tags are not populating correctly.  This impacts the tabs functionality in the /language-masters/en/adventures.html page.  

Also, the cq:tags appear in the .content.xml file for the pages, but not in the properties screen in Admin UI.

**Comment by godanny86** [comment]
PR #84 resolves this.
