### ISSUE TITLE
Assign Cloud Configuration on WKND root page

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-guides-wknd#67]
the Configuration > Cloud Configuration should be set to /conf/wknd on. Right now it's empty.

/mnt/overlay/wcm/core/content/sites/properties.html?item=%2Fcontent%2Fwknd

<img width="994" alt="Screen Shot 2019-12-16 at 2 55 14 PM" src="https://user-images.githubusercontent.com/4974276/70949979-23c88500-2014-11ea-9717-330ac34eaa47.png">

or is that something that the Project Archetype should do?

**Comment by gabrielwalt** [comment]
This also relates to https://github.com/adobe/aem-project-archetype/issues/310.

**Comment by gknobloch** [comment]
I'd agree the archetype should take care of this while generating the site, hence we'd need to fix
- the archteype
- this project

**Comment by gknobloch** [comment]
Would it make sense for /content/dam/wknd too? And similarly in the archetype?

**Comment by gabrielwalt** [comment]
Agreed, it seems that DAM also needs such a `cq:conf` property.

**Comment by godanny86** [comment]
fixed with pr #74
