### ISSUE TITLE
Interested in this project

### ISSUE THREAD

**Issue by CodeByAlex** [adobe/aem-guides-wknd#86]
@godanny86 - if you have a moment, could you please reach out?

Wondering if there is a better way to automate the compilation of htl so that the storybook youve created can use that data output rather than html copied and pasted in which would make it more dynamic.

twitter: @codebyalex
website codebyalex.com

or please respond here

**Comment by godanny86** [comment]
Hi @CodeByAlex!

Thanks for reaching out! Yes, I agree there should be a better way to integrate storybook with AEM components then copy + paste :) 

I've had a few thoughts. One would be to look at a node-based HTL compiler [0], [1] to compile component scripts from ui.apps. 

Other ideas would be to somehow point to an instance of AEM/page and dynamically pull in the rendered markup and smartly identify which components/stories it belongs to.

Definitely open to other creative ideas!

[0] - https://github.com/adobe/htlengine
[1] - https://www.npmjs.com/package/htl-compiler

**Comment by CodeByAlex** [comment]
I love that you brought up those options @godanny86. I’ve worked on the storybook open source project so I’m familiar with the architecture. I’ve seen a few implementations so far to achieve what you have done in this project which is to use the storybook react app or storybook html app to display aem components. I think a good solution would be to create a native storybook aem library that uses one of the above compilers. This is a new effort and I’ve got another dev who will be working with me on this. Would you want to be involved in that too?

**Comment by godanny86** [comment]
Hey @CodeByAlex absolutely. I'll reach out over email.

**Comment by godanny86** [comment]
if anyone is interested in contributing to this effort, checkout: https://github.com/storybookjs/aem
