### ISSUE TITLE
Maven version dependencies are mismatched

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-guides-wknd#91]
Using the maven release plugin, didn't catch all of the dependencies leaving some mismatched:

https://github.com/adobe/aem-guides-wknd/blob/1fbe0244e13a2e326c733666a61d57a5f74bf2ca/ui.content/pom.xml#L62

**Should be**
```xml
 <dependencies>
        <dependency>
         <groupId>com.adobe.aem.guides</groupId>
           <artifactId>aem-guides-wknd.ui.apps</artifactId>
           <version>0.0.3-SNAPSHOT</version>
            </dependency>
 </dependencies>
```

**Actual**

```xml
 <dependencies>
      <dependency>
       <groupId>com.adobe.aem.guides</groupId>
      <artifactId>aem-guides-wknd.ui.apps</artifactId>
       <version>0.0.1-SNAPSHOT</version>
        </dependency>
</dependencies>
```

**Comment by godanny86** [comment]
thanks @bstopp for reporting!

**Comment by davidjgonzalez** [comment]
probably is easiest to update them to use `${project.version}` since i dont think there is a use case for ever having them diverge across the project. This was its very clear that theyre intended to be kept in sync as well.
