### ISSUE TITLE
WKND core bundle is not getting active

### ISSUE THREAD

**Issue by GauravRameshTiwari** [adobe/aem-guides-wknd#92]
When I am installing core bundle in osgi below two dependency can not be resolved 

com.day.cq.search,version=[1.3,2) -- Cannot be resolved

org.apache.sling.api.resource,version=[2.11,3) -- Cannot be resolved.

Apache Sling API bundle version is 2.16.4 
Can anyone suggest something.

**Comment by godanny86** [comment]
hi @GauravRameshTiwari 

What version of AEM are you using? http://localhost:4502/libs/granite/operations/content/systemoverview.html

**Comment by GauravRameshTiwari** [comment]
I am using 6.4 ,

**Comment by godanny86** [comment]
ah ok, are you just installing the latest release? https://github.com/adobe/aem-guides-wknd/releases or are you building the project yourself?

At a minimum you will need AEM 6.4 + Service Pack 4 to be compatible with [AEM Core Components 2.8.0](https://github.com/adobe/aem-core-wcm-components#system-requirements)

**Comment by GauravRameshTiwari** [comment]
Hi I have downloaded from github latest release  I do not have service pack 4.
Is there anything that can be done I am doing this to get familiar with the concepts of 6.2 onward sling model cf xf etc .
Can you suggest any workaround ?
Thank you.

**Comment by godanny86** [comment]
If you log into https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html can you download the latest service pack? I will add a package later today to the release that is compatible with 6.4.4

**Comment by GauravRameshTiwari** [comment]
Sorry but I am unable to download this as it requires enterprise support. I am using training license and doing this on my personal laptop for learning .

**Comment by godanny86** [comment]
Added a classic profile to deploy to 6.4.8+ and 6.5.5+ with PR #105
