### ISSUE TITLE
WKND Sites Project - Core (aem-guides-wknd.core) bundle not Active on AEM 6.3.3

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-guides-wknd#93]
WKND Reference Site - 0.0.2 - https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-0.0.2 cannot be used on AEM 6.3.3

With ref to this https://github.com/adobe/aem-guides-wknd/issues/92#issuecomment-594214345 if AEM 6.4 is required, can we mention somewhere in README. Thanks!

```
com.day.cq.search,version=[1.3,2) -- Cannot be resolved
com.day.cq.wcm.api,version=[1.27,2) -- Cannot be resolved
org.apache.commons.lang3,version=[3.6,4) -- Cannot be resolved
org.apache.sling.api.resource,version=[2.11,3) -- Cannot be resolved
```

![Screen Shot 2020-03-12 at 6 03 02 PM](https://user-images.githubusercontent.com/902972/76575027-075dac80-648c-11ea-848f-181a9bf6a7fa.png)

**Comment by godanny86** [comment]
Updated project with `classic` profile to be backward compatible with PR #105
