### ISSUE TITLE
Question: Using ui.frontend folder for SASS and React?

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-guides-wknd#95]
Question: 
When using the new AEM Archetype ([v23](https://github.com/adobe/aem-project-archetype/releases/tag/aem-project-archetype-23)) general/react/angular sources are built into "ui.frontend" folder. 

While this project (wknd) is a great resource/refer to build codebases for new projects, the "ui.frontend" in wknd is used for "sass" and this works great.

How can we build a new codebase using both react-app(when built with archetype 23) and sass (file structure as defined in wknd) i.e., AEM + React + SASS ?

**Comment by godanny86** [comment]
hi @ksurendra good question. If you just want to add Sass support to the React ui.frontend module generated by the archetype you should be able to follow: https://create-react-app.dev/docs/adding-a-sass-stylesheet. The ui.frontend (React) module is actually a webpack project based on the Create React App.

**Comment by godanny86** [comment]
Working example can now be found at: https://github.com/adobe/aem-guides-wknd-spa/blob/React/latest/ui.frontend/package.json#L19

**Comment by ksurendra** [comment]
Thanks @godanny86 for following up on this.
