### ISSUE TITLE
Mobile emulator path hard coded

### ISSUE THREAD

**Issue by knennigtri** [adobe/aem-guides-wknd#97]
/conf/wknd/settings/wcm/templates/< template-name >/structure/jcr:content
+ cq:deviceGroups = /etc/mobile/groups/responsive

Because this value is hard coded in, there isn't the resolution process of etc > libs/settings > apps/settings > conf/settings and therefore, you cannot easily create custom emulators.

Like the html5page template-type, the value should be
+ cq:deviceGroups = mobile/groups/responsive

This also probably needs to be updated under /content/wknd/jcr:content too.

**Comment by godanny86** [comment]
Thanks @knennigtri for raising. If you have time, do you mind checking if this is the default for projects generated by the AEM archetype...?

**Comment by knennigtri** [comment]
Ah. Good call. I can confirm that Archetype 23 does indeed generate the absolute path here. I suppose this needs to be submitted to that project then too?

**Comment by godanny86** [comment]
If you don't mind :)
