### ISSUE TITLE
HTTP:X-Forwarded-For in rewrite rules rejecting IPV6

### ISSUE THREAD

**Issue by vampirofear** [adobe/aem-guides-wknd#98]
In default rewrite rules of dispatcher there is a rule with text:
# Prevent X-FORWARDED-FOR spoofing
RewriteCond %{HTTP:X-Forwarded-For} !^$
RewriteCond %{HTTP:X-Forwarded-For} !^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
RewriteRule .* - [F]

This rule is taking as condition and IPv4, however connection is rejected if is an IPv6.
if an IPV6 is on this header the connection is returned with state 403 and refused.

**Comment by godanny86** [comment]
hi @vampirofear this project is generated by the AEM Project Archetype: https://github.com/adobe/aem-project-archetype. Do you mind re-posting this issue there?
